package mocks

import mock "github.com/stretchr/testify/mock"

// Notifications is an autogenerated mock type for the Notifications type
type Notifications struct {
	mock.Mock
}

// Send provides a mock function with given fields: recipient, message
func (_m *Notifications) Send(recipient string, message string) error {
	ret := _m.Called(recipient, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(recipient, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
