package mocks

import mock "github.com/stretchr/testify/mock"

// Shouter is an autogenerated mock type for the Shouter type
type Shouter struct {
	mock.Mock
}

// Send provides a mock function with given fields: recipients, templateName, data
func (_m *Shouter) Send(recipients []string, templateName string, data map[string]string) error {
	ret := _m.Called(recipients, templateName, data)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, string, map[string]string) error); ok {
		r0 = rf(recipients, templateName, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
