package mocks

import mock "github.com/stretchr/testify/mock"

// Templates is an autogenerated mock type for the Templates type
type Templates struct {
	mock.Mock
}

// Render provides a mock function with given fields: templateName, data
func (_m *Templates) Render(templateName string, data map[string]string) (string, error) {
	ret := _m.Called(templateName, data)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, map[string]string) string); ok {
		r0 = rf(templateName, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, map[string]string) error); ok {
		r1 = rf(templateName, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
